ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300

SCREEN_WIDTH = COLS * TILE_SIZE
SCREEN_HEIGHT = ROWS * TILE_SIZE
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 14


#enemy constants
SPAWN_COOLDOWN = 400

#turret constants
TURRET_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 1
LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5